### ISSUE TITLE
[신규기능] 설치형 slack mattermost 알람 지원 

### ISSUE THREAD

**Issue by hkjang** [tadpolehub/TadpoleDBHub_enterprise#14]
금일 릴리즈 노트 잘 받았습니다~ 
여러가지 알람 기능 넣어주셔서 감사합니다. 

내부망에서는 mattermost 와 같은 설치형을 많이 쓰고 있는데요~ 
혹시 mattermost 알람 기능 지원 로드맵에 있을까요?

**Comment by hangum** [comment]
@hkjang 일단은 솔루션을 살펴보겠습니다.  
https://docs.mattermost.com/developer/webhooks-incoming.html 라면 slack에 넣어서 쏴도 되겠다 싶어요.

**Comment by hkjang** [comment]
답변 감사합니다~
