### ISSUE TITLE
api hub 에러 메시지 수정 요청

### ISSUE THREAD

**Issue by hkjang** [tadpolehub/TadpoleDBHub_enterprise#20]
#### 버전 : tadpole 2.0.0
api hub에서 에러 메시지 수정 검토 부탁 드립니다. 

### api hub api는 존재하고, api hub 사용여부 no일 경우 
- 기존 :  404 - not found your request url
- 변경 :  권한 없음에 대한 메시지 

### api hub 사용여부 yes이고, api key 틀릴 경우 
- 기존  : 404 - not found your request url 
- 변경 : api key 가 틀림에 대한 메시지

**Comment by hangum** [comment]
@hkjang  개선할 수 있도록 하겠습니다. 
감사합니다.

**Comment by hangum** [comment]
{"status":401,"code":"401","message":"URL found. However, the URL is disabled. Please Set API support to YES.URL is /search/city","devMessage":""}

이렇게 개선되었습니다. 감사합니다.
