### ISSUE TITLE
[api hub] 테드폴 쿼리 테이블 api 제작 용도 insert문 요청

### ISSUE THREAD

**Issue by hkjang** [tadpolehub/TadpoleDBHub_enterprise#24]
tadpole 이 사용하고 있는 쿼리 테이블을 api hub를 이용해 api로 하나 만드려고 하는데요~ 

api 만드려는 목적은 
다른 시스템에서 등록된 쿼리를 한꺼번에 가져와 
특정 유저 이름으로 테드폴 디비의 user_db_resource_data,user_db_resource테이블에 다수 넣고자 합니다. 

아래 두개 db 테이블을 이용하면 될것으로 생각되긴 하는데요~ 
테이블에 seq와 같은 컬럼도 있고 해서 insert쿼리를 직접 요청 드리는게 좋을 것 같아 문의차 이슈 남깁니다~ 

혹시 답변 가능할까요?

user_db_resource
user_db_resource_data

**Comment by hangum** [comment]
안녕하세요. 관련 쿼리를 정리해서 메일 드릴게요. 

나의 iPhone에서 보냄

2019. 6. 19. 오후 3:27, hkjang <notifications@github.com> 작성:
