### ISSUE TITLE
SQL파일 가져오기 기능에서 인코딩 지정이 가능하면 좋겠습니다.

### ISSUE THREAD

**Issue by jeongjaehong** [tadpolehub/TadpoleDBHub_enterprise#3]
SQL 파일 가져오기를 할때 인코딩 정보를 지정할 수 있나요?
다운로드 받은 파일도 utf-8이고 export받은 sql파일도 utf-8입니다. 
그런데 업로드 하고 나서 자료를 조회하면 첨부된 이미지처럼 ?????? 로 깨져서 들어가고 있습니다.

<img width="580" alt="image" src="https://user-images.githubusercontent.com/859932/47700038-4c4abf80-dc58-11e8-951e-16baefd17593.png">

<img width="974" alt="image" src="https://user-images.githubusercontent.com/859932/47700025-3b01b300-dc58-11e8-8c00-6686e5aabc94.png">

**Comment by hangum** [comment]
한글 깨지던가요?  나는 잘 되던데... 한번더 해봐야겠네요.

**Comment by jeongjaehong** [comment]
디비 연결정보 등록할때  utf-8 로 하지않고 none로 설정해 놓아서 발생한 문제였습니다. 

<img width="487" alt="image" src="https://user-images.githubusercontent.com/859932/47701635-cc275880-dc5d-11e8-9ed1-98411b792376.png">
