### ISSUE TITLE
SQL Editor 에서 트랜젝션 처리여부를 묻는 대화상자에 대해서...

### ISSUE THREAD

**Issue by jeongjaehong** [tadpolehub/TadpoleDBHub_enterprise#31]
에디터를 열었다가 바로 닫아도 트랜젝션을 어떻게 할거냐는 대화상자가 표시됩니다.

진행중인 트랜젝션이 있는지 확인 후 메시지를 표시하면 좋을것 같습니다.
 
<img width="709" alt="image" src="https://user-images.githubusercontent.com/859932/62665448-50132b80-b9ba-11e9-9320-a0d1bed9ee36.png">

**Comment by hangum** [comment]
개선할 수 있도록 하겠습니다.

**Comment by hangum** [comment]
v2.1.3 r8에서 개선되었습니다.
