### ISSUE TITLE
데이터 직접수정 에디터의 개선 건의.

### ISSUE THREAD

**Issue by jeongjaehong** [tadpolehub/TadpoleDBHub_enterprise#35]
데이터 직접 수정을 데이터가 엄청 많은(?) 테이블을 대상으로 수행하면 올챙이가 폭주하면서 브라우져가 다운됩니다.  ㅠㅠ

해당테이블의 레코드 건수가 특정 한계치를 넘어갈 경우 최대 1000개 정도로 제한을 해서 select해서 표시하거나 사용자가 where절을 추가하여 새로고침 하기 전에는 에티더 열리면서 자동으로 데이터를 로딩하지 않도록 하면 좋을것 같습니다.

현재는 무조건 에디터가 열리면서 해당 테이블의 모든 자료를 로딩하기 때문에 데이터가 많은 테이블을 대상으로 직접수정 에디터를 열 경우 올챙이가 다운 되는 현상이 발생합니다.

<img width="576" alt="image" src="https://user-images.githubusercontent.com/859932/65935380-dba5b780-e453-11e9-89ba-3410e0edf239.png">

**Comment by hangum** [comment]
- 개선했습니다.
