### ISSUE TITLE
사용자 정보 추가 후 조회시 오류발생.

### ISSUE THREAD

**Issue by jeongjaehong** [tadpolehub/TadpoleDBHub_enterprise#7]
새로운 사용자를 추가한 후에 ... 한번도 로그인 하지 않은 상태에서.

새로고침 또는 사용자 정보 조회화면을 닫았다가 다시 열때.

정보를 조회해서 표시하는 중에 오류가 발생합니다.

로그인 정보 같은게 없어서 그러는듯 합니다.

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/859932/49359621-0cc13880-f71a-11e8-9733-9489bbed009a.png">

**Comment by hangum** [comment]
말씀하신 사항으로 나는 에러가 확실하네요. 
수정했습니다.
