### ISSUE TITLE
Google OTP QR 코드 링크 아닌 이미지로 제공 요청

### ISSUE THREAD

**Issue by hkjang** [tadpolehub/TadpoleDBHub_enterprise#72]
사내망 특성상 테드폴디비허브 구글 OTP 2단계 인증 적용 시
url을 외부로 옮기기에 다소 불편한 점이 있습니다. 

QR코드 링크 아닌 이미지로 제공 요청 가능한지 문의드립니다.

**Comment by hkjang** [comment]
추가로 google OTP 앱에서 title 이 이메일 주소만 표시되는데
이메일 주소 앞에 TadpoleDBHub 라는 명칭이 title prefix 로 들어갔으면 합니다.

**Comment by hkjang** [comment]
구글 OTP사용을 사용자 관리에서 생성으로 해 주고, 보안설정에서 OTP강제 사용을 설정해줘도 
로그인시 OTP를 묻지않고 로그인되는 오류가 있습니다.

**Comment by hkjang** [comment]
version 2.3.0 사용 중입니다.

**Comment by hangum** [comment]
@hkjang 
어드민 로그인 -> 메뉴 -> 어드민 -> 시스템환경설정 -> (툴바) 로그인 설정에서 로그인 시에 OTP 확인 필수를 선택해 주세요. 
![image](https://user-images.githubusercontent.com/1335915/87486646-af6fc600-c676-11ea-9993-ffa80418a3ed.png)

**Comment by hangum** [comment]
@hkjang  추가로 google OTP 앱에서 title 이 이메일 주소만 표시되는데
이메일 주소 앞에 TadpoleDBHub 라는 명칭이 title prefix 로 들어갔으면 합니다.

-->  백로그에 넣도록 할게요.

**Comment by hangum** [comment]
사내망 특성상 테드폴디비허브 구글 OTP 2단계 인증 적용 시
url을 외부로 옮기기에 다소 불편한 점이 있습니다.

QR코드 링크 아닌 이미지로 제공 요청 가능한지 문의드립니다.

-->  가끔 이미지가 제대로 표시가 안될때가 있어서요. 좀더 확인해 보겠습니다.

**Comment by hangum** [comment]
미쳐 생각각하지 못했는데... 간단한데 무척 편하네요. 
![IMG_6295](https://user-images.githubusercontent.com/1335915/87487310-4be69800-c678-11ea-9e23-96f20ecc03ec.PNG)

**Comment by hkjang** [comment]
빠른 답변 및 대응 감사합니다. 대표님
