### ISSUE TITLE
오브젝트 컴파일 에디터 에서도 포맷 기능이 있으면 좋겠습니다~~~

### ISSUE THREAD

**Issue by jeongjaehong** [tadpolehub/TadpoleDBHub_enterprise#74]
오브젝트 컴파일 에디터 에서도 포맷 기능이 있으면 좋겠습니다~~~

<img width="928" alt="image" src="https://user-images.githubusercontent.com/859932/90079323-88261a80-dd42-11ea-8a0a-c0b9a68b9ec2.png">

**Comment by hangum** [comment]
블럭을 지정하고 맥의 경우 cmd + shift + F 를 눌러주세요.
전체는 cmd + shift + F를 누르시면 됩니다.
![image](https://user-images.githubusercontent.com/1335915/141038427-6576c9d8-1db8-4f6e-95bf-264a64248576.png)
