### ISSUE TITLE
테드폴디비허브 유저 타임아웃 300분 이상 설정 가능 여부 문의

### ISSUE THREAD

**Issue by hkjang** [tadpolehub/TadpoleDBHub_enterprise#77]

**Comment by hkjang** [comment]
테드폴디비허브 유저 타임아웃 300분 이상 설정 할수 있을까요?

원하는 설정 : 1일 타임아웃

**Comment by hangum** [comment]
안녕하세요. 
보통은 5분 10분 단위로 설정하도록 하는데요. 1일까지 설정 가능하게 하시는 이유가 있을까요?

**Comment by hkjang** [comment]
@hangum 폐쇄망에서 사용 중이라 너무 자주 세션 만료되면 사용이 불편합니다. 
OTP 적용 후에는 더더욱 그러합니다.

**Comment by hangum** [comment]
@hkjang 시간을 좀더 늘려 놓을수 있도록 하겠습니다.
