### ISSUE TITLE
메인 화면에서 데이터 베이스에 대한 센션은 유지 중인데... sql에디터의 세션만 끊긴경우....

### ISSUE THREAD

**Issue by jeongjaehong** [tadpolehub/TadpoleDBHub_enterprise#78]
Reconnect 기능이 있었으면 좋겠습니다.

에디터 창에서 편집중이던 쿼리를 실행할때 커넥션이 닫혔다고 에러 메시지만 뜨는데...

다시 연결할지 묻은 대화상자를 표시하거나... 

재연결 버튼을 도구모음에 넣어주시면 좋을것 같습니다. ^^;

**Comment by hangum** [comment]
버그로 인한것인데 지금은 개선되었습니다.
