### ISSUE TITLE
php 문법으로 변환할때, 키워드 앞 또는 뒤에 공백이 없어 오류가 발생합니다.

### ISSUE THREAD

**Issue by jeongjaehong** [tadpolehub/TadpoleDBHub_enterprise#81]
$query .= "FROM"; 이 아니라
$query .= "    FROM   "; 이것처럼 공백이 있어야.. 윗쪽과 아랫쪽의 다른 문장과 공백없이 연결되어 syntax 오류가 발생하지 않도록 생성되어야 할것 같습니다.

<img width="862" alt="image" src="https://user-images.githubusercontent.com/859932/120784610-39629f00-c567-11eb-99c1-c05e09d5e85f.png">

**Comment by hangum** [comment]
감사합니다.
