### ISSUE TITLE
postgreSQL 12.3 에서 테이블 직접 수정 메뉴 클릭시 첨부와 같은 오류가 발생하면서 직접수정 기능이 작동하지 않습니다.

### ISSUE THREAD

**Issue by jeongjaehong** [tadpolehub/TadpoleDBHub_enterprise#82]
<img width="977" alt="image" src="https://user-images.githubusercontent.com/859932/121650136-3b32e200-cad4-11eb-9897-1029fb178b13.png">

**Comment by hangum** [comment]
수정했습니다.

postgresql이 이전버전에서는 스키마를 보여주지 않다가 보여주는 과정에서 코드를 놓쳤네요.
