### ISSUE TITLE
postgreSQL 에서 컬럼 상세 내역에 컬럼의 데이터 길이가 표시되지 않습니다.

### ISSUE THREAD

**Issue by jeongjaehong** [tadpolehub/TadpoleDBHub_enterprise#83]
<img width="854" alt="image" src="https://user-images.githubusercontent.com/859932/121825065-5d527d00-cceb-11eb-8611-6dfacb82c5bf.png">

**Comment by hangum** [comment]
네 표시할수 있도록 하겠습니다.
