### ISSUE TITLE
데이터 베이스 정보에서보면 테이블 코멘트가 등록되어 있는데 테이블 목록 뷰에서는 표시가 안됩니다.

### ISSUE THREAD

**Issue by jeongjaehong** [tadpolehub/TadpoleDBHub_enterprise#84]
<img width="912" alt="image" src="https://user-images.githubusercontent.com/859932/125541510-853d71c3-cf77-442f-bfa7-f69b5143035a.png">

**Comment by hangum** [comment]
v3.0.0 r1에서  적용될 예정입니다.
